### ISSUE TITLE
IE11 - Zoom level 2 symbology not shown for imported ESRI Air Quality Layer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1019]
Tested build: http://fgpv.cloudapp.net/demo/v1.0.1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
Esri Air Quality layer URL: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

Only zoom level 2 symbology was not shown. The rest zoom levels are OK.

![image](https://cloud.githubusercontent.com/assets/18723160/17260217/2008915c-559d-11e6-865f-3b7354d5d5c0.png)

**Comment by james-rae** [comment]
Cannot reproduce.  The above screenshot was taken in IE11 (you can tell because the scale flags are missing).
However, when I load the same url / same layer in IE11, my scale flags are present.  Is it possible we have different versions of IE11?  Mine is `11.0.9600.18376` ; I would expect we are all the same as it is patched by the patch bot.

**Comment by spencerwahl** [comment]
WOMM too (version `11.0.9600.18349`)

**Comment by IsabellaPan** [comment]
My IE11 version: 11.0.9600.18349
Update Version: 11.0.32 (KB3160005)

**Comment by james-rae** [comment]
Isabella updated her version today, the error still occurs consistently.  The following is in the IE console, but is fairly unhelpful as IE won't indicate any line numbers where the errors are occurring.

These are the useful lines I copied out of the console

```
XMLHttpRequest: Network Error 0x2ee2, Could not complete the operation due to error 00002ee2.

Unable to load http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer/2?f=json status: 0

"RequestError"
```

It still WOMM

**Comment by mweech** [comment]
I have same IE and Update version as Isabella and cannot reproduce..

**Comment by james-rae** [comment]
`00002ee2` in decimal is `12002`, which is `The request has timed out.` Still doesn't explain why only Isabella gets the error

**Comment by alyec** [comment]
I was able to reproduce with IE on build v1.0.1:
![2016-08-04 09_30_12-fgp viewer - internet explorer](https://cloud.githubusercontent.com/assets/7646414/17403520/2942d9c0-5a26-11e6-90ee-7f7f11e571bd.png)

It was fixed on my system when testing with an intermediate build (4f6b962):
![2016-08-04 09_30_12-fgp viewer - internet explorer](https://cloud.githubusercontent.com/assets/7646414/17403527/2e8565ba-5a26-11e6-8267-439fae5e9500.png)

**Comment by IsabellaPan** [comment]
I can still see this issue in today's new build. 
URL: http://fgpv.cloudapp.net/demo/v1.0.2-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

**Comment by james-rae** [comment]
Nov 10 2016 -- still happens on Isabella's PC (`v1.4.0-rc3`) but not on James' PC

**Comment by IsabellaPan** [comment]
Nov 9 2016 - still couple of issues for this user-added scale dependency layer
1. All the four zoom level layers displayed eye icon, no magnifying glass shown up
2. "Layer out of scale" icons not displayed for any zoom levels
3. Datagrid for zoom level 2 cannot be loaded
![image](https://cloud.githubusercontent.com/assets/18723160/20152878/2346a470-a68e-11e6-8c77-78fa87304623.png)

**Comment by IsabellaPan** [comment]
Nov 10 tested it again with build v1.4.0-5. Still an issue with IE11

**Comment by IsabellaPan** [comment]
Nov 15, it seems this issue is intermittent - it works today on IE11 with build v1.4.0-5
Will close this issue for now
