### ISSUE TITLE
IE11 - Help overlapped with Language section on Left Sided Menu

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1510]
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-2/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

Help is not aligned well, it should be above the horizontal line, not falling under the line to be stacked with Language section. Français should be a little bit up from the 2nd horizontal line as well.
![image](https://cloud.githubusercontent.com/assets/18723160/21185240/d3f3045c-c1dd-11e6-8217-dd3b33a34db6.png)

**Comment by AleksueiR** [comment]
Fixed by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1553 PR.

**Comment by IsabellaPan** [comment]
Jan 12 2017
Still an issue, tested with build http://fgpv.cloudapp.net/demo/v1.5.0-10/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

"Help" should be in the place above the line, but now it is located below the line and getting close to "Language"
![image](https://cloud.githubusercontent.com/assets/18723160/21897227/f993dc6e-d8b6-11e6-93ae-963ee15b93b8.png)

**Comment by AleksueiR** [comment]
Can you close this as duplicate? I accidentally created another one issue here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1578 and this one will be referenced by a PR. Thanks.

**Comment by IsabellaPan** [comment]
Feb 8 2017
No longer an issue, verified with build:
http://fgpv.cloudapp.net/demo/v1.5.0-rc3/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
