### ISSUE TITLE
Long Column headings will need to be truncated in  datatable 

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2151]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily15/prod/samples/index-samples.html

Test data http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_census_of_agriculture_2011_ccs/MapServer
Select "**Characteristics of farm operators**

Long column names will need to be truncated or column should be resized to fit the header text. 

![image](https://user-images.githubusercontent.com/18539315/28085796-cbec3aa0-664a-11e7-92da-259a01f32b23.png)
![image](https://user-images.githubusercontent.com/18539315/28086242-57bf9418-664c-11e7-8c8c-767086f29441.png)

**Comment by JahidAhmed** [comment]
Looks like it's fixed by PR #2149.

**Comment by AleksueiR** [comment]
@JahidAhmed Overlapping will still happen even with #2149 if the config author specify narrow columns in the config.
