### ISSUE TITLE
bug: identify breaks

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#491]
Identify breaks when it tries to interrogate a layer ("STB EOS 2014 CI ON 30m v2") in error state.

Root cause as determined by @jolevesq is the esriTile type has not been created.  Tile layers are then being added as esriDynamic which allows for identify queries to be made, which cause the error.  By creating esriTile, service will load as its proper type which does not support identify and would automatically eliminate the issue.

**Comment by james-rae** [comment]
Root cause appears to how the legend is processing a Tile Service consumed as a Dynamic Layer.  It is possible to do this --> a MapService containing a tile set exposes the ability to output a map-sized picture instead of a set of tiles.  

In file `legend-entry.service.js`, method `DYNAMIC_ENTRY_MASTER_GROUP.init`, the code is assuming the layer object will contain properties specific to layer-based map services. 

To temporarily fix the issue, we have removed this layer from the config

```
"id":"stb_eos",
  "name": "STB EOS 2014 CI ON 30m v2",
  "layerType":"esriTile",
  "url":"http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT_CBCT_GEOM_3857/MapServer"
}
```

Long term solution, we can either

1. Decide not to support visualizing Tile Services as Dynamic Layers. If so, we should add some type of error checking.
2. Support Tile Services as Dynamic Layers, and adjust the above function to omit the various legend child items if the certain properties are not present in the Layer Object.

**Comment by AleksueiR** [comment]
Short term fix is addressed by PR#494.

@james-rae, James, could you create a task to implement a long term solution?

**Comment by mweech** [comment]
PR#494 only addressed a patch for the release.  bug remains and will be fixed under this issue.

**Comment by mweech** [comment]
Do not support Tile Services loading as Dynamic Layers.  Disable identify query on tile layers.

**Comment by jolevesq** [comment]
Easy way to deal with this is to set the entry in the legend the same way as wmsGenerator (legendEntryFactory.singleEntryItem). @james-rae do you know a way to get a kind of symbology for a esriTile? If not I will have to remove the symbology node from the legend entry.

**Comment by james-rae** [comment]
For now, I would suggest picking a placeholder image to use (show same for all Tiles), and mark the location with a `//TODO` statement.  We can debate later what a good image will be.  One idea would be to screenshot a basemap and crop a 32x32 image.  But any placeholder will do.

**Comment by mweech** [comment]
@AleksueiR may wish to provide some input re: image to use.

**Comment by jolevesq** [comment]
@james-rae @AleksueiR  for now it looks like the image layer. @mweech I think need to implement something to disable the visibility button when layer is not in the same projection. It is not necessary but for a user it will be easier to understand then click on the visibility icon and nothing shows up. I can do as part of this issue or we can send this for later. What do you prefer?

**Comment by AleksueiR** [comment]
If we can't show the layer, shouldn't we remove it entirely?

**Comment by jolevesq** [comment]
@AleksueiR we can see it when we switch to a basemap with the same projection. I think we should let the layer there. Maybe we should add a tooltip to say wrong projection (need to switch) so the user will understand. If the layer is not there, the user will never know to change basemap to see the layer. He will just wondering why the layer is not there.

**Comment by AleksueiR** [comment]
@jolevesq Thanks for explanations, I've made a new issue to address how this notification should be handled.
For now, I think, disabling the visibility toggle (as per your code) is the best way.

**Comment by mweech** [comment]
it may be worthwhile to consider an enhancement where the projection system the viewer initially utilizes is dictated by the WKID of the tile services being requested.  if two different tile sets, one in each projection system is specified, preference would still go to LCC.
